### ISSUE TITLE
Testing APIs

### ISSUE THREAD

**Issue by DrGoshD** [Realstranger01/Com-PET-ible#1]
Testing APIs, before approving the project.

**Comment by kelenyathi** [comment]
Completed proposal and chose the wrong APIs (back-end not front-end). Omar asked us to check APIs were correct. We found front-end APIs to use then sent to Omar who said we needed to test the APIs

**Comment by ReactByHamza** [comment]
Kele sent the project proposal to Omar and he advised us to test the API's before approving the proposal so I try to test both API's but the resources for the URL wasn't loading.

**Comment by DrGoshD** [comment]
Had to subscribe to the APIs on RapidAPI to have access and successfully test them.
